-- Create the database
CREATE DATABASE `shopify_assistant`;

-- Remove the table if it already exists
DROP TABLE IF EXISTS `Imported_Order`;
-- Create the table the orders are imported into
CREATE TABLE `Imported_Order` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Tracking_Number` VARCHAR(255),
  `Name` VARCHAR(255),
  `Email` VARCHAR(255),
  `Financial_Status` VARCHAR(255),
  `Paid_at` DATETIME,
  `Fulfillment_Status` VARCHAR(255),
  `Fulfilled_at` DATETIME,
  `Accepts_Marketing` TINYINT(1),
  `Currency` VARCHAR(255),
  `Subtotal` DECIMAL(13,2),
  `Shipping` DECIMAL(13,2),
  `Taxes` DECIMAL(13,2),
  `Total` DECIMAL(13,2),
  `Discount_Code` VARCHAR(255),
  `Discount_Amount` DECIMAL(13,2),
  `Shipping_Method` VARCHAR(255),
  `Created_at` DATETIME,
  `Lineitem_quantity` INT(11) UNSIGNED,
  `Lineitem_name` VARCHAR(255),
  `Lineitem_price` DECIMAL(13,2),
  `Lineitem_compare_at_price` DECIMAL(13,2),
  `Lineitem_sku` VARCHAR(255),
  `Lineitem_requires_shipping` TINYINT(1),
  `Lineitem_taxable` TINYINT(1),
  `Lineitem_fulfillment_status` VARCHAR(255),
  `Billing_Name` VARCHAR(255),
  `Billing_Street` TEXT,
  `Billing_Address1` TEXT,
  `Billing_Address2` TEXT,
  `Billing_Company` VARCHAR(255),
  `Billing_City` VARCHAR(255),
  `Billing_Zip` VARCHAR(255),
  `Billing_Province` VARCHAR(255),
  `Billing_Country` VARCHAR(255),
  `Billing_Phone` VARCHAR(255),
  `Shipping_Name` VARCHAR(255),
  `Shipping_Street` TEXT,
  `Shipping_Address1` TEXT,
  `Shipping_Address2` TEXT,
  `Shipping_Company` VARCHAR(255),
  `Shipping_City` VARCHAR(255),
  `Shipping_Zip` VARCHAR(255),
  `Shipping_Province` VARCHAR(255),
  `Shipping_Country` VARCHAR(255),
  `Shipping_Phone` VARCHAR(255),
  `Notes` TEXT,
  `Note_Attributes` TEXT,
  `Cancelled_at` DATETIME,
  `Payment_Method` VARCHAR(255),
  `Payment_Reference` VARCHAR(255),
  `Refunded_Amount` DECIMAL(13,2),
  `Vendor` VARCHAR(255),
  `Shopify_Order_Id` BIGINT(20),
  `Tags` VARCHAR(255),
  `Risk_Level` VARCHAR(255),
  `Source` VARCHAR(255),
  `Lineitem_discount` DECIMAL(13,2),
  `Tax_1_Name` VARCHAR(255),
  `Tax_1_Value` VARCHAR(255),
  `Tax_2_Name` VARCHAR(255),
  `Tax_2_Value` VARCHAR(255),
  `Tax_3_Name` VARCHAR(255),
  `Tax_3_Value` VARCHAR(255),
  `Tax_4_Name` VARCHAR(255),
  `Tax_4_Value` VARCHAR(255),
  `Tax_5_Name` VARCHAR(255),
  `Tax_5_Value` VARCHAR(255),
  `Phone` VARCHAR(255),
  `Receipt_Number`  VARCHAR(255),
  `Row_Created_Datetime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `Row_Last_Updated_DateTime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create the user for the application to use
CREATE USER 'your-user-here'@'localhost' IDENTIFIED BY 'your-password-here';
CREATE DATABASE `shopify_assistant`;
GRANT DELETE, INSERT, SELECT, UPDATE ON shopify_assistant.* TO 'shopify-assistant'@'localhost';
